version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  back:
    restart: always
    build:
      context: .
    env_file:
      - .env
    ports:
      - 4000:4000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - "postgres"
    command: npm run dev

networks:
  default:
    external:
      name: ecommerce-network
